In [1]:
import pandas as pd

In [ ]:
dir(pd)

# Markdown Cell

In [3]:
df=pd.read_csv("/content/sample_data/california_housing_train.csv") # dataset available in sample_ta

In [4]:
df.head(15)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
5,-114.58,33.63,29.0,1387.0,236.0,671.0,239.0,3.3438,74000.0
6,-114.58,33.61,25.0,2907.0,680.0,1841.0,633.0,2.6768,82400.0
7,-114.59,34.83,41.0,812.0,168.0,375.0,158.0,1.7083,48500.0
8,-114.59,33.61,34.0,4789.0,1175.0,3134.0,1056.0,2.1782,58400.0
9,-114.60,34.83,46.0,1497.0,309.0,787.0,271.0,2.1908,48100.0
10,-114.60,33.62,16.0,3741.0,801.0,2434.0,824.0,2.6797,86500.0
11,-114.60,33.60,21.0,1988.0,483.0,1182.0,437.0,1.6250,62000.0
12,-114.61,34.84,48.0,1291.0,248.0,580.0,211.0,2.1571,48600.0
13,-114.61,34.83,31.0,2478.0,464.0,1346.0,479.0,3.2120,70400.0
14,-114.63,32.76,15.0,1448.0,378.0,949.0,300.0,0.8585,45000.0

In [5]:
df.tail(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16990,-124.22,41.73,28.0,3003.0,699.0,1530.0,653.0,1.7038,78300.0
16991,-124.23,41.75,11.0,3159.0,616.0,1343.0,479.0,2.4805,73200.0
16992,-124.23,40.81,52.0,1112.0,209.0,544.0,172.0,3.3462,50800.0
16993,-124.23,40.54,52.0,2694.0,453.0,1152.0,435.0,3.0806,106700.0
16994,-124.25,40.28,32.0,1430.0,419.0,434.0,187.0,1.9417,76100.0
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [6]:
# First upload Salaries.csv
#df=pd.read_csv("/content/Salaries.csv")
df=pd.read_csv("Salaries.csv")

In [7]:
df

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
..        ...        ...  ...      ...     ...     ...
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

[78 rows x 6 columns]

In [8]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [9]:
df.dtypes

rank          object
discipline    object
phd            int64
service        int64
sex           object
salary         int64
dtype: object

In [ ]:
df.tail(10)

         rank discipline  phd  service     sex  salary
68   AsstProf          A    4        2  Female   77500
69       Prof          A   28        7  Female  116450
70   AsstProf          A    8        3  Female   78500
71  AssocProf          B   12        9  Female   71065
72       Prof          B   24       15  Female  161101
73       Prof          B   18       10  Female  105450
74  AssocProf          B   19        6  Female  104542
75       Prof          B   17       17  Female  124312
76       Prof          A   28       14  Female  109954
77       Prof          A   23       15  Female  109646

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

In [11]:
df['rank']

0          Prof
1          Prof
2          Prof
3          Prof
4          Prof
        ...
73         Prof
74    AssocProf
75         Prof
76         Prof
77         Prof
Name: rank, Length: 78, dtype: object

In [12]:
df.describe()

             phd    service         salary
count  78.000000  78.000000      78.000000
mean   19.705128  15.051282  108023.782051
std    12.498425  12.139768   28293.661022
min     1.000000   0.000000   57800.000000
25%    10.250000   5.250000   88612.500000
50%    18.500000  14.500000  104671.000000
75%    27.750000  20.750000  126774.750000
max    56.000000  51.000000  186960.000000

In [ ]:
df.max()

rank            Prof
discipline         B
phd               56
service           51
sex             Male
salary        186960
dtype: object

In [ ]:
df.min()

rank          AssocProf
discipline            A
phd                   1
service               0
sex              Female
salary            57800
dtype: object

In [ ]:
df.mean()

<ipython-input-28-c61f0c8f89b5>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.mean()

phd            19.705128
service        15.051282
salary     108023.782051
dtype: float64

In [13]:
df.phd.describe()

count    78.000000
mean     19.705128
std      12.498425
min       1.000000
25%      10.250000
50%      18.500000
75%      27.750000
max      56.000000
Name: phd, dtype: float64

In [ ]:
df.phd.quantile(0.25)

10.25

In [ ]:
df.salary.quantile(0.50)

In [ ]:
df.salary.quantile(0.75)

126774.75

In [ ]:
df.std()

In [ ]:
df_50=df.head(50)

In [ ]:
df_50.mean()

<ipython-input-36-abcf5df04292>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df_50.mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [ ]:
df_50

         rank discipline  phd  service     sex  salary
0        Prof          B   56       49    Male  186960
1        Prof          A   12        6    Male   93000
2        Prof          A   23       20    Male  110515
3        Prof          A   40       31    Male  131205
4        Prof          B   20       18    Male  104800
5        Prof          A   20       20    Male  122400
6   AssocProf          A   20       17    Male   81285
7        Prof          A   18       18    Male  126300
8        Prof          A   29       19    Male   94350
9        Prof          A   51       51    Male   57800
10       Prof          B   39       33    Male  128250
11       Prof          B   23       23    Male  134778
12   AsstProf          B    1        0    Male   88000
13       Prof          B   35       33    Male  162200
14       Prof          B   25       19    Male  153750
15       Prof          B   17        3    Male  150480
16   AsstProf          B    8        3    Male   75044
17   AsstProf          B    4        0    Male   92000
18       Prof          A   19        7    Male  107300
19       Prof          A   29       27    Male  150500
20   AsstProf          B    4        4    Male   92000
21       Prof          A   33       30    Male  103106
22   AsstProf          A    4        2    Male   73000
23   AsstProf          A    2        0    Male   85000
24       Prof          A   30       23    Male   91100
25       Prof          B   35       31    Male   99418
26       Prof          A   38       19    Male  148750
27       Prof          A   45       43    Male  155865
28   AsstProf          B    7        2    Male   91300
29       Prof          B   21       20    Male  123683
30  AssocProf          B    9        7    Male  107008
31       Prof          B   22       21    Male  155750
32       Prof          A   27       19    Male  103275
33       Prof          B   18       18    Male  120000
34  AssocProf          B   12        8    Male  119800
35       Prof          B   28       23    Male  126933
36       Prof          B   45       45    Male  146856
37       Prof          A   20        8    Male  102000
38   AsstProf          B    4        3    Male   91000
39       Prof          B   18       18  Female  129000
40       Prof          A   39       36  Female  137000
41  AssocProf          A   13        8  Female   74830
42   AsstProf          B    4        2  Female   80225
43   AsstProf          B    5        0  Female   77000
44       Prof          B   23       19  Female  151768
45       Prof          B   25       25  Female  140096
46   AsstProf          B   11        3  Female   74692
47  AssocProf          B   11       11  Female  103613
48       Prof          B   17       17  Female  111512
49       Prof          B   17       18  Female  122960

In [ ]:
df.head(50).mean()

<ipython-input-26-56442511a41d>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.head(50).mean()

phd            21.52
service        17.60
salary     113789.14
dtype: float64

In [ ]:
#Selecting a column
df.salary # does not work if column name contains blank space or dot (eg. "No. of Columns")
#           for that enclose column name inside square bracket.

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [ ]:
df['salary'] # will work if column name has blank space or dot eg. df["No. of Columns"]

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [16]:
result1=df.salary
result1

0     186960
1      93000
2     110515
3     131205
4     104800
       ...
73    105450
74    104542
75    124312
76    109954
77    109646
Name: salary, Length: 78, dtype: int64

In [ ]:
# 2 data structures in pandas: 1. Series 2. DataFrame
# Pandas Series: is a one-dimensional labeled array whose object size cannot be changed.
#
# Pandas DataFrame: is a two-dimensional structure with columns and rows whose size can be changed.
# You can also think of it as a dictionary of Series objects.
type(result1)

pandas.core.series.Series

In [14]:
result2=df[['salary','rank']]

In [15]:
result2

    salary       rank
0   186960       Prof
1    93000       Prof
2   110515       Prof
3   131205       Prof
4   104800       Prof
..     ...        ...
73  105450       Prof
74  104542  AssocProf
75  124312       Prof
76  109954       Prof
77  109646       Prof

[78 rows x 2 columns]

In [ ]:
type(result2)

pandas.core.frame.DataFrame

In [ ]:
df.columns

Index(['rank', 'discipline', 'phd', 'service', 'sex', 'salary'], dtype='object')

In [17]:
# Extract particular columns in a new dataframe
newdf=df[['salary','service','phd']]
newdf

    salary  service  phd
0   186960       49   56
1    93000        6   12
2   110515       20   23
3   131205       31   40
4   104800       18   20
..     ...      ...  ...
73  105450       10   18
74  104542        6   19
75  124312       17   17
76  109954       14   28
77  109646       15   23

[78 rows x 3 columns]

In [18]:
df['discipline'].value_counts() # category and its value

B    42
A    36
Name: discipline, dtype: int64

In [19]:
df['rank'].value_counts()

Prof         46
AsstProf     19
AssocProf    13
Name: rank, dtype: int64

Calculate the basic statistics for the Phd column;

Find how many values in the Phd column (use count method);

Calculate the average Phd;

In [ ]:
df.phd.describe()

In [ ]:
df.phd.count()

In [ ]:
df.phd.mean()

In [20]:
# in rank 3 values: Asso,Asst,Prof. Group by this and find mean of each category
df.groupby(['rank']).mean() # group by rank and finds mean of all numeric columns

<ipython-input-20-2ed0b5db6a4e>:2: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['rank']).mean() # group by rank and finds mean of all numeric columns

                 phd    service         salary
rank
AssocProf  15.076923  11.307692   91786.230769
AsstProf    5.052632   2.210526   81362.789474
Prof       27.065217  21.413043  123624.804348

In [ ]:
df.groupby(['sex']).mean()

In [21]:
df.groupby(["discipline"]).count()

            rank  phd  service  sex  salary
discipline
A             36   36       36   36      36
B             42   42       42   42      42

In [ ]:
df.groupby(["discipline","rank"]).count()

                      phd  service  sex  salary
discipline rank
A          AssocProf    5        5    5       5
           AsstProf     8        8    8       8
           Prof        23       23   23      23
B          AssocProf    8        8    8       8
           AsstProf    11       11   11      11
           Prof        23       23   23      23

In [ ]:
df.groupby(["discipline","rank","sex"]).count()

In [ ]:
df.groupby(["discipline","rank","sex"]).mean() # avg sal of discipline B's Male Prof is: 137989.076923

                                   phd    service         salary
discipline rank      sex
A          AssocProf Female  18.500000  15.500000   72128.500000
                     Male    20.000000  17.000000   81285.000000
           AsstProf  Female   4.833333   2.500000   72933.333333
                     Male     3.000000   1.000000   79000.000000
           Prof      Female  26.500000  16.125000  109631.875000
                     Male    28.933333  22.733333  113164.400000
B          AssocProf Female  13.500000   8.833333   99435.666667
                     Male    10.500000   7.500000  113404.000000
           AsstProf  Female   6.600000   2.600000   84189.800000
                     Male     4.666667   2.000000   88224.000000
           Prof      Female  21.500000  17.900000  131836.200000
                     Male    29.538462  25.846154  137989.076923

In [ ]:
df.groupby('rank')[['salary','phd']].mean() # group by rank and find mean of specified columns only

In [ ]:
grouped=df.groupby('rank') # saving in variable grouped

In [ ]:
grouped

In [ ]:
for g in grouped: # to display records of grouped variable
  print(g)

In [ ]:
df[df.salary>120000]

    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
3   Prof          A   40       31    Male  131205
5   Prof          A   20       20    Male  122400
7   Prof          A   18       18    Male  126300
10  Prof          B   39       33    Male  128250
11  Prof          B   23       23    Male  134778
13  Prof          B   35       33    Male  162200
14  Prof          B   25       19    Male  153750
15  Prof          B   17        3    Male  150480
19  Prof          A   29       27    Male  150500
26  Prof          A   38       19    Male  148750
27  Prof          A   45       43    Male  155865
29  Prof          B   21       20    Male  123683
31  Prof          B   22       21    Male  155750
35  Prof          B   28       23    Male  126933
36  Prof          B   45       45    Male  146856
39  Prof          B   18       18  Female  129000
40  Prof          A   39       36  Female  137000
44  Prof          B   23       19  Female  151768
45  Prof          B   25       25  Female  140096
49  Prof          B   17       18  Female  122960
51  Prof          B   20       14  Female  127512
58  Prof          B   36       26  Female  144651
72  Prof          B   24       15  Female  161101
75  Prof          B   17       17  Female  124312

In [ ]:
df.shape

(78, 6)

In [ ]:
df.shape[1]

6

In [ ]:
df[df.salary>120000].shape[0] # count of prof having sal > 120000

In [ ]:
df[df.salary>120000].count()

In [ ]:
newdf=df[(df['sex']=='Male') & (df['salary']>150000)]
newdf

In [ ]:
# newdf.count()
# OR
newdf.shape[0]

In [ ]:
df[df['rank']!='Prof'].shape[0]

In [ ]:
df[(df['service']>15) | (df['salary']>100000)]
#df[(df['service']>15) | (df['salary']>100000)].shape[0]

In [ ]:
df # will display all records

In [ ]:
# to extract only particular index record - say 5th index record
df[5] # will raise error

In [ ]:
df.iloc[77] # iloc -> index location for row

In [ ]:
df.iloc[1:4, 0:3]  # row 1 to 3, col 0 to 2

In [ ]:
df.iloc[0:10,0:3] # 0 to 9 records, 0 to 2 columns

In [ ]:
df.iloc[0:2,] # rows 0 to 1 and all columns, Or df.iloc[0:2]

In [ ]:
df.iloc[:,4] #all rows, index 4 column

In [ ]:
df.iloc[:,0:3]

In [ ]:
df.iloc[[10,20,22,24],] # only particular rows with all columns df.iloc[[10,20,22,24]]

In [ ]:
df.loc[:,['rank','sex']] # without mentioning index no. - mention col name

In [ ]:
df.loc[[0,1,2],['discipline','rank']]

In [ ]:
df.iloc[::5] # start value:0, end value:77, step value:5, all rows and columns with step value 5

In [ ]:
df.iloc[10:30:4]

In [ ]:
df.iloc[::-1] # all records in reverse order

Aggregation Function in Pandas
Aggreation - Computing a summary statistic about each group

In [ ]:
dir(df) # functions that can be applied on dataframe

['T',
 '_AXIS_LEN',
 '_AXIS_ORDERS',
 '_AXIS_TO_AXIS_NUMBER',
 '_HANDLED_TYPES',
 '__abs__',
 '__add__',
 '__and__',
 '__annotations__',
 '__array__',
 '__array_priority__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__copy__',
 '__dataframe__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__finalize__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__imod__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__round__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_accessors',
 '_accum_func',
 '_add_numeric_operations',
 '_agg_by_level',
 '_agg_examples_doc',
 '_agg_summary_and_see_also_doc',
 '_align_frame',
 '_align_series',
 '_append',
 '_arith_method',
 '_as_manager',
 '_attrs',
 '_box_col_values',
 '_can_fast_transpose',
 '_check_inplace_and_allows_duplicate_labels',
 '_check_inplace_setting',
 '_check_is_chained_assignment_possible',
 '_check_label_or_level_ambiguity',
 '_check_setitem_copy',
 '_clear_item_cache',
 '_clip_with_one_bound',
 '_clip_with_scalar',
 '_cmp_method',
 '_combine_frame',
 '_consolidate',
 '_consolidate_inplace',
 '_construct_axes_dict',
 '_construct_axes_from_arguments',
 '_construct_result',
 '_constructor',
 '_constructor_sliced',
 '_convert',
 '_count_level',
 '_data',
 '_dir_additions',
 '_dir_deletions',
 '_dispatch_frame_op',
 '_drop_axis',
 '_drop_labels_or_levels',
 '_ensure_valid_index',
 '_find_valid_index',
 '_flags',
 '_from_arrays',
 '_get_agg_axis',
 '_get_axis',
 '_get_axis_name',
 '_get_axis_number',
 '_get_axis_resolvers',
 '_get_block_manager_axis',
 '_get_bool_data',
 '_get_cleaned_column_resolvers',
 '_get_column_array',
 '_get_index_resolvers',
 '_get_item_cache',
 '_get_label_or_level_values',
 '_get_numeric_data',
 '_get_value',
 '_getitem_bool_array',
 '_getitem_multilevel',
 '_gotitem',
 '_hidden_attrs',
 '_indexed_same',
 '_info_axis',
 '_info_axis_name',
 '_info_axis_number',
 '_info_repr',
 '_init_mgr',
 '_inplace_method',
 '_internal_names',
 '_internal_names_set',
 '_is_copy',
 '_is_homogeneous_type',
 '_is_label_or_level_reference',
 '_is_label_reference',
 '_is_level_reference',
 '_is_mixed_type',
 '_is_view',
 '_iset_item',
 '_iset_item_mgr',
 '_iset_not_inplace',
 '_item_cache',
 '_iter_column_arrays',
 '_ixs',
 '_join_compat',
 '_logical_func',
 '_logical_method',
 '_maybe_cache_changed',
 '_maybe_update_cacher',
 '_metadata',
 '_mgr',
 '_min_count_stat_function',
 '_needs_reindex_multi',
 '_protect_consolidate',
 '_reduce',
 '_reduce_axis1',
 '_reindex_axes',
 '_reindex_columns',
 '_reindex_index',
 '_reindex_multi',
 '_reindex_with_indexers',
 '_rename',
 '_replace_columnwise',
 '_repr_data_resource_',
 '_repr_fits_horizontal_',
 '_repr_fits_vertical_',
 '_repr_html_',
 '_repr_latex_',
 '_reset_cache',
 '_reset_cacher',
 '_sanitize_column',
 '_series',
 '_set_axis',
 '_set_axis_name',
 '_set_axis_nocheck',
 '_set_is_copy',
 '_set_item',
 '_set_item_frame_value',
 '_set_item_mgr',
 '_set_value',
 '_setitem_array',
 '_setitem_frame',
 '_setitem_slice',
 '_slice',
 '_stat_axis',
 '_stat_axis_name',
 '_stat_axis_number',
 '_stat_function',
 '_stat_function_ddof',
 '_take',
 '_take_with_is_copy',
 '_to_dict_of_blocks',
 '_typ',
 '_update_inplace',
 '_validate_dtype',
 '_values',
 '_where',
 'abs',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'append',
 'apply',
 'applymap',
 'asfreq',
 'asof',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'backfill',
 'between_time',
 'bfill',
 'bool',
 'boxplot',
 'clip',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'discipline',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'ffill',
 'fillna',
 'filter',
 'first',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_dict',
 'from_records',
 'ge',
 'get',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iteritems',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'last',
 'last_valid_index',
 'le',
 'loc',
 'lookup',
 'lt',
 'mad',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'nunique',
 'pad',
 'pct_change',
 'phd',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'salary',
 'sample',
 'select_dtypes',
 'sem',
 'service',
 'set_axis',
 'set_flags',
 'set_index',
 'sex',
 'shape',
 'shift',
 'size',
 'skew',
 'slice_shift',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swapaxes',
 'swaplevel',
 'tail',
 'take',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_gbq',
 'to_hdf',
 'to_html',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs']

Common aggregation functions are:min,max,count,sum,prod,mean,median,mode,mad,std,var

In [ ]:
# Compute group sums or means
# Compute group sizes or counts
# agg() or aggregate()  - useful when multiple statistics are computed per column
# Here's how to calculate the Mean Absolute Deviation - mad().
#Step 1: Calculate the mean.
#Step 2: Calculate how far away each data point is from the mean using positive distances. These are called absolute deviations.
#Step 3: Add those deviations together.
#Step 4: Divide the sum by the number of data points.

df[['phd','salary']].agg(['min','mean','max','mad','std'])

In [ ]:
df[['salary']].agg('skew')

salary    0.452103
dtype: float64

In [ ]:
df[['salary']].agg('kurt')

salary   -0.401713
dtype: float64

In [ ]:
df.var()

In [ ]:
df.values

In [ ]:
df.sem() #std error of mean - Standard error i.e.Sigma / square root of n